source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NBInfiniteBannerView_Example', :exclusive => true do
  pod "NBInfiniteBannerView", :path => "../"
end

target 'NBInfiniteBannerView_Tests', :exclusive => true do
  pod "NBInfiniteBannerView", :path => "../"

  
end
